schema_version = "1.0.0"

id = "unrealengine_assets_exporter"
version = "4.3.3"
name = "Unreal Engine Assets Exporter"
tagline = "Allows to batch export and import in Unreal Engine"
maintainer = "Loux Xavier (BleuRaven) xavierloux.loux@gmail.com"
type = "add-on"

website = "https://github.com/xavier150/Blender-For-UnrealEngine-Addons/"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = ["2024 Xavier Loux. All rights reserved",]

platforms = ['windows-x64', 'linux-x64', 'macos-x64', 'macos-arm64', 'windows-arm64']

[permissions]
files = "Import/export FBX from/to disk"