schema_version = "1.0.0"

id = "unrealengine_assets_exporter"
version = "4.3.6"
name = "Unreal Engine Assets Exporter"
tagline = "Allows to batch export and import in Unreal Engine"
maintainer = "Loux Xavier (BleuRaven) xavierloux.loux@gmail.com"
type = "add-on"

website = "https://github.com/xavier150/Blender-For-UnrealEngine-Addons/"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2024 Xavier Loux",
  "2013 Blender Foundation",
  "2006-2012 assimp team",
  "2013 Campbell Barton",
  "2014 Bastien Montagne",
]

[build]
paths_exclude_pattern = [
  "fbxio/generator/",
  "fbxio/run_generator.py",
  "fbxio/io_scene_fbx_2_83/", 
  "fbxio/io_scene_fbx_2_93/", 
  "fbxio/io_scene_fbx_3_1/", 
  "fbxio/io_scene_fbx_3_2/", 
  "fbxio/io_scene_fbx_3_3/", 
  "fbxio/io_scene_fbx_3_4/", 
  "fbxio/io_scene_fbx_3_5/", 
  "fbxio/io_scene_fbx_3_6/"
]

[permissions]
files = "Import/export FBX from/to disk"
clipboard = "Copy generated script paths"

